server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Ocultar versión de nginx
    server_tokens off;

    # Compresión gzip
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;

    # Sin cache — entorno de desarrollo, todo se descarga siempre fresco
    add_header Cache-Control "no-cache, no-store, must-revalidate";

    # Fallback SPA — todas las rutas van a index.html para que React Router las maneje
    location / {
        try_files $uri $uri/ /index.html;
    }
}
